services:
  postgres:
    image: postgres:15
    container_name: quarkus_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-quarkus-social}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-quarkus-social}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - quarkus-net

  app:
    # constrói a imagem usando seu Dockerfile do Quarkus
    build:
      context: .
      dockerfile: Dockerfile
    image: code-with-quarkus:local          # tag local opcional
    container_name: quarkus_app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      QUARKUS_PROFILE: docker
      QUARKUS_DATASOURCE_DEVSERVICES_ENABLED: "false"
      QUARKUS_HTTP_PORT: "8080"
      QUARKUS_HTTP_HOST: "0.0.0.0"
      # Configuração do banco de dados para o ambiente Docker
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-quarkus-social}
      QUARKUS_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "8080:8080"
    networks:
      - quarkus-net

networks:
  quarkus-net:
    driver: bridge

volumes:
  pgdata:
