version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: quarkus_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quarkus-social
    networks:
      - quarkus-net

  app:
    image: code-with-quarkus
    container_name: quarkus_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/quarkus-social
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
    networks:
      - quarkus-net

networks:
  quarkus-net:

